version: '3.4'

services:

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  movie.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


  music.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


